name: sliver_tools
description: A set of useful sliver tools that are missing from the flutter framework
version: 0.2.10
homepage: https://github.com/Kavantix
repository: https://github.com/Kavantix/sliver_tools
issue_tracker: https://github.com/Kavantix/sliver_tools/issues

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  logging:

flutter:
